@startuml
'aws lib
!include <awslib/AWSCommon>
!include <awslib/Groups/Generic>
!include <awslib/Groups/AWSCloud>
!include <awslib/Groups/VPC>
!include <awslib/Groups/PublicSubnet>
!include <awslib/Groups/PrivateSubnet>
!include <awslib/NetworkingContentDelivery/ElasticLoadBalancingApplicationLoadBalancer>

!include <awslib/NetworkingContentDelivery/VPCInternetGateway>

!include <awslib/Compute/EC2>

!include <awslib/Containers/ElasticContainerRegistry>
!include <awslib/Containers/ElasticContainerService>
!include <awslib/Containers/Fargate>

!include <awslib/ApplicationIntegration/APIGateway>
!include <awslib/ApplicationIntegration/AppSync>
!include <awslib/Database/DynamoDB>

'common library
!include <archimate/Archimate>

skinparam linetype ortho

AWSCloudGroup(cloud) {

    VPCGroup(vpc, "VPC"){
        VPCInternetGateway(ig, "Internet Gateway", "chigirh-cicd-igw")

        GenericGroup(components3, "CI/CD") #Transparent{
            ElasticContainerService(ecs, "trainning-liubang-cluster", "") #Transparent
            ElasticContainerRegistry(ecr, "trainning-liubang-repository", "") #Transparent
        }

        PublicSubnetGroup(subnet1, "Public Subnet1"){
            ElasticLoadBalancingApplicationLoadBalancer(alb,"Application Load Balancer", "cicd-handson-alb") #Transparent

            EC2(ec2_1, "Judge0 Service", "chigirh-judge0-api-ec2") #Transparent

            GenericGroup(components1, "training-liubang-service") #Transparent {
                rectangle "$FargateIMG()\nAWS Fargate" as fargate #Transparent
            }
        }
        
        PublicSubnetGroup(subnet2, "Public Subnet2"){
        
        AppSync(appsysc, "AWS AppSync", "")  #Transparent{
                Application_Component(asSchema, "スキーマ")
                Application_Component(asResolver, "リゾルバ")
            }

            rectangle "$DynamoDBIMG()\nAmazon DynamoDB" as dynamodb

            APIGateway(agw,"API Gateway", "") #Transparent
        }    
    }
}

' layout
ig -[hidden]r- subnet1
subnet1 -[hidden]d- subnet2
subnet1 -[hidden]r- components3
ecs -[hidden]d- ecr


'
ecs -l- fargate
ecs -d- ecr

alb -d- ec2_1
alb -r- fargate

agw -d- appsysc
appsysc -r- dynamodb


@enduml